apiVersion: v1
kind: Service
metadata:
  name: greeting-api
  labels:
    app: greeting-api
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    app: greeting-api
  type: ClusterIP